%YAML:1.0

# output directory
output_dir: "/root/larvio_results/"

# switches
if_FEJ: 1    # 0(false) or 1(true)
estimate_extrin: 1    # 0(false) or 1(true)
estimate_td: 1    # 0(false) or 1(true)
calib_imu_instrinsic: 1    # 0(false) or 1(true)

# camera instrinsic
camera_model: "pinhole"         # only support "pinhole"
distortion_model: "equidistant" # only support "radtan" and "equidistant"
resolution_width: 848
resolution_height: 800
intrinsics:
   fx: 283.9606359631292
   fy: 283.944037787027
   cx: 422.61969756330876
   cy: 400.9851394912655
distortion_coeffs:
   k1: -0.013082218864165409
   k2: 0.07195407379287126
   p1: -0.07455735633046572
   p2: 0.02000513035322955

# imu-camera extrinsic, including spacial and temporal parameters
T_cam_imu: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data:
    [-0.99988447,  0.01102751,  0.01046158, -0.0515686,
     -0.01087233, -0.99983172,  0.01477586,  0.02340238,
      0.01062276,  0.01466041,  0.9998361,   0.04414308,
      0.,          0.,          0.,          1.        ]
td: 0.0014674939209408273

# TODO: if calibrate camera instrinsic online

# visual front-end parameters
pyramid_levels: 2
patch_size: 21
fast_threshold: 10
max_iteration: 30
track_precision: 0.01
ransac_threshold: 1
max_features_num: 50
min_distance: 20
flag_equalize: 0    # 0(false) or 1(true)
pub_frequency: 30

# window size
sw_size: 20

# online reset thresholds
position_std_threshold: 8.0
rotation_threshold: 0.2618
translation_threshold: 0.1
tracking_rate_threshold: 0.1

# feature triangulation parameters
least_observation_number: 3
max_track_len: 6
feature_translation_threshold: -1.0

# imu and camera measurement noise parameters
noise_gyro: 5.0e-3
noise_acc: 7.0e-1
noise_gyro_bias: 5.0e-3
noise_acc_bias: 1.0e-0
noise_feature: 0.008

# filter intial covariance
initial_covariance_orientation: 4e-4
initial_covariance_velocity: 0.25
initial_covariance_position: 0.0
initial_covariance_gyro_bias: 4e-4
initial_covariance_acc_bias: 0.01
initial_covariance_extrin_rot: 3.0462e-8
initial_covariance_extrin_trans: 9e-8

# fej settings
reset_fej_threshold: 10.11

# zupt settings
if_ZUPT_valid: 1    # 0(false) or 1(true)
zupt_max_feature_dis: 2e-3
zupt_noise_v: 1e-2    # std
zupt_noise_p: 1e-2
zupt_noise_q: 3.4e-2

# static initialization setting
static_duration: 1.0

# measurement rate
imu_rate: 200
img_rate: 30

# augmented feature state settings
max_features_in_one_grid: 1     # pure msckf if set to 0
aug_grid_rows: 8
aug_grid_cols: 8
feature_idp_dim: 1              # 1 or 3

# if apply Schmidt filter
use_schmidt: 0    # 0(false) or 1(true)
